"""Issuer health as a latent, pre-computed timeline.

Two design decisions worth stating up front.

**Health is pre-computed for the whole horizon before any policy runs.** A bank
does not go down because an agent retried against it, so the outage timeline
must not depend on the agent's actions. Pre-computing makes that structural
rather than a thing we have to remember not to violate, and it is what lets
two policies face bit-identical infrastructure conditions.

**Issuer names are fictional.** The obvious move is to use real bank names, and
it demos better. But the outage frequencies here are modelled, not measured --
NPCI publishes monthly aggregates, not incident traces -- so attaching them to
a named real institution would be asserting something about that institution's
reliability that this project has no evidence for. The banks below are
archetypes drawn to match the *structure* of the Indian issuing market (large
private, large public-sector, regional, payments bank) without impersonating
any member of it.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, auto

from kintsugi import calibration as cal
from kintsugi.rng import exponential, uniform

MINUTES_PER_DAY = 1440


class HealthState(Enum):
    HEALTHY = auto()
    DEGRADED = auto()
    OUTAGE = auto()

    @property
    def success_multiplier(self) -> float:
        return _MULTIPLIER[self]


_MULTIPLIER = {
    HealthState.HEALTHY: 1.0,
    HealthState.DEGRADED: cal.DEGRADED_SUCCESS_MULTIPLIER.v,
    HealthState.OUTAGE: cal.OUTAGE_SUCCESS_MULTIPLIER.v,
}


class IssuerTier(Enum):
    """Market archetypes with genuinely different reliability profiles."""

    LARGE_PRIVATE = auto()
    LARGE_PUBLIC = auto()
    REGIONAL = auto()
    PAYMENTS_BANK = auto()

    @property
    def incident_multiplier(self) -> float:
        """Scales the base outage and degradation rates.

        Assumption, stated plainly: larger private issuers run more reliable
        rails than regional ones. This is the ordering the RBI's own uptime
        disclosures imply, but the magnitudes here are ours.
        """
        return _TIER_INCIDENT[self]


_TIER_INCIDENT = {
    IssuerTier.LARGE_PRIVATE: 0.6,
    IssuerTier.LARGE_PUBLIC: 1.4,
    IssuerTier.REGIONAL: 2.1,
    IssuerTier.PAYMENTS_BANK: 0.8,
}


@dataclass(frozen=True, slots=True)
class Issuer:
    code: str
    name: str
    tier: IssuerTier
    share: float
    """Share of payment volume routed to this issuer."""


#: A synthetic issuing market. Shares are shaped like the real one -- a few
#: large issuers carrying most volume, a long tail of smaller ones -- without
#: claiming to reproduce any particular institution's numbers.
DEFAULT_ISSUERS: tuple[Issuer, ...] = (
    Issuer("MRDN", "Meridian Bank",     IssuerTier.LARGE_PRIVATE, 0.24),
    Issuer("ASTR", "Astra Bank",        IssuerTier.LARGE_PRIVATE, 0.19),
    Issuer("BHRT", "Bharat Sarva Bank", IssuerTier.LARGE_PUBLIC,  0.17),
    Issuer("SMDR", "Samudra Bank",      IssuerTier.LARGE_PUBLIC,  0.12),
    Issuer("KVRI", "Kaveri Bank",       IssuerTier.REGIONAL,      0.09),
    Issuer("PRVT", "Parvat Bank",       IssuerTier.REGIONAL,      0.07),
    Issuer("NVPY", "NovaPay Payments",  IssuerTier.PAYMENTS_BANK, 0.07),
    Issuer("QKPY", "QuickPay Payments", IssuerTier.PAYMENTS_BANK, 0.05),
)


@dataclass(frozen=True, slots=True)
class HealthInterval:
    start: int
    end: int
    state: HealthState


class IssuerHealthTimeline:
    """The latent health history of one issuer across the whole horizon.

    Generated by alternating healthy periods with incidents drawn from
    exponential waiting times. Incidents are sampled independently per issuer:
    correlated multi-bank outages (an NPCI-side event) are deliberately *not*
    modelled, which makes this a conservative world for our agent -- rail
    switching would look better than it does here if outages clustered.
    """

    __slots__ = ("issuer", "horizon", "_intervals", "_starts")

    def __init__(self, issuer: Issuer, horizon_minutes: int, seed: int) -> None:
        self.issuer = issuer
        self.horizon = horizon_minutes
        self._intervals = self._generate(issuer, horizon_minutes, seed)
        self._starts = [iv.start for iv in self._intervals]

    @staticmethod
    def _generate(
        issuer: Issuer, horizon: int, seed: int
    ) -> list[HealthInterval]:
        mult = issuer.tier.incident_multiplier
        outage_per_min = (
            cal.ISSUER_OUTAGE_RATE_PER_DAY.v * mult / MINUTES_PER_DAY)
        degraded_per_min = (
            cal.ISSUER_DEGRADED_RATE_PER_DAY.v * mult / MINUTES_PER_DAY)
        total_rate = outage_per_min + degraded_per_min
        p_outage = outage_per_min / total_rate

        intervals: list[HealthInterval] = []
        t = 0
        i = 0
        while t < horizon:
            gap = exponential(1.0 / total_rate, seed, issuer.code, "gap", i)
            start = t + int(gap)
            if start >= horizon:
                break

            is_outage = uniform(seed, issuer.code, "kind", i) < p_outage
            state = HealthState.OUTAGE if is_outage else HealthState.DEGRADED
            mean_dur = (
                cal.ISSUER_OUTAGE_MEAN_MINUTES.v if is_outage
                else cal.ISSUER_DEGRADED_MEAN_MINUTES.v
            )
            duration = max(
                5, int(exponential(mean_dur, seed, issuer.code, "dur", i)))
            end = min(horizon, start + duration)

            if start > t:
                intervals.append(HealthInterval(t, start, HealthState.HEALTHY))
            intervals.append(HealthInterval(start, end, state))
            t = end
            i += 1

        if t < horizon:
            intervals.append(HealthInterval(t, horizon, HealthState.HEALTHY))
        return intervals

    def state_at(self, minute: int) -> HealthState:
        # Intervals are contiguous and sorted; linear scan from a bisect point.
        lo, hi = 0, len(self._intervals) - 1
        while lo <= hi:
            mid = (lo + hi) // 2
            iv = self._intervals[mid]
            if minute < iv.start:
                hi = mid - 1
            elif minute >= iv.end:
                lo = mid + 1
            else:
                return iv.state
        return HealthState.HEALTHY

    def multiplier_at(self, minute: int) -> float:
        return self.state_at(minute).success_multiplier

    def incidents(self) -> list[HealthInterval]:
        """Non-healthy intervals -- the ground truth the monitor must infer."""
        return [iv for iv in self._intervals if iv.state is not HealthState.HEALTHY]

    def downtime_minutes(self) -> int:
        return sum(iv.end - iv.start for iv in self.incidents())


class IssuerRegistry:
    """All issuer timelines for one simulated world."""

    __slots__ = ("issuers", "timelines")

    def __init__(
        self,
        horizon_minutes: int,
        seed: int,
        issuers: tuple[Issuer, ...] = DEFAULT_ISSUERS,
    ) -> None:
        self.issuers = {i.code: i for i in issuers}
        self.timelines = {
            i.code: IssuerHealthTimeline(i, horizon_minutes, seed)
            for i in issuers
        }

    def multiplier(self, issuer_code: str, minute: int) -> float:
        return self.timelines[issuer_code].multiplier_at(minute)

    def state(self, issuer_code: str, minute: int) -> HealthState:
        return self.timelines[issuer_code].state_at(minute)

    def total_downtime(self) -> dict[str, int]:
        return {c: t.downtime_minutes() for c, t in self.timelines.items()}
